name: growgrid
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.dev.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/config/certs

  influxdb2:
    image: influxdb:2-alpine
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      INFLUXD_HTTP_AUTH_ENABLED: "false"
      INFLUXD_REPORTING_DISABLED: "true"
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: growgrid
      DOCKER_INFLUXDB_INIT_BUCKET: growgrid
      INFLUXD_HTTP_BIND_ADDRESS: :8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      influxdb2:
        condition: service_started
      mosquitto:
        condition: service_started
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ./telegraf/telegraf.dev.conf:/etc/telegraf/telegraf.conf:ro
      - ./certs:/etc/telegraf/certs:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - INFLUXDB_ORG=growgrid
      - INFLUXDB_BUCKET=growgrid
      - INFLUXDB_URL=http://influxdb2:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    depends_on:
      influxdb2:
        condition: service_started
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  influxdb2-data:
  nodered-data:
  grafana-data:
