name: growgrid
x-common-sec: &common-sec
  read_only: true
  cap_drop: [ALL]
  security_opt:
    - no-new-privileges:true

services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "192.168.178.45:1883:1883"
    environment:
      - MQTT_USERNAME_FILE=/run/secrets/mqtt_username
      - MQTT_PASSWORD_FILE=/run/secrets/mqtt_password
    secrets:
      - mqtt_username
      - mqtt_password
    volumes:
      - /srv/growgrid/appdata/mosquitto:/mosquitto/config:ro
      - /srv/growgrid/data/mosquitto/data:/mosquitto/data
      - /srv/growgrid/data/mosquitto/log:/mosquitto/log
    <<: [*common-sec]
    tmpfs:
      - /tmp

  influxdb2:
    image: influxdb:2.7-alpine
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - "192.168.178.45:8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influx_username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influx_password
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXD_HTTP_BIND_ADDRESS: :8086
      DOCKER_INFLUXDB_INIT_RETENTION: 2160h
    env_file:
      - /srv/growgrid/.env
    secrets:
      - influx_username
      - influx_password
    volumes:
      - /srv/growgrid/data/influxdb2:/var/lib/influxdb2
      - /srv/growgrid/appdata/influxdb2/config:/etc/influxdb2
    <<: [*common-sec]
    read_only: false

  telegraf:
    image: telegraf:1.30-alpine
    container_name: telegraf
    depends_on:
      influxdb2:
        condition: service_healthy
      mosquitto:
        condition: service_started
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUX_TOKEN_FILE: /run/secrets/influx_token_telegraf
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_USERNAME_FILE: /run/secrets/mqtt_username
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
      MQTT_TOPIC: ${MQTT_TOPIC}
    env_file:
      - /srv/growgrid/.env
    secrets:
      - influx_token_telegraf
      - mqtt_username
      - mqtt_password
    volumes:
      - /srv/projects/growgrid/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    <<: [*common-sec]

  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    restart: unless-stopped
    ports:
      - "192.168.178.45:3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      INFLUXDB_TOKEN__FILE: /run/secrets/influx_token_grafana
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_URL: ${INFLUXDB_URL}
    env_file:
      - /srv/growgrid/.env
    secrets:
      - grafana_admin_user
      - grafana_admin_password
      - influx_token_grafana
    volumes:
      - /srv/growgrid/data/grafana:/var/lib/grafana
      - /srv/projects/growgrid/grafana/provisioning:/etc/grafana/provisioning:ro
      - /srv/projects/growgrid/grafana/dashboards:/var/lib/grafana/dashboards:ro
    <<: [*common-sec]
    read_only: false

secrets:
  mqtt_username:
    file: /srv/growgrid/secrets/mqtt_username
  mqtt_password:
    file: /srv/growgrid/secrets/mqtt_password
  influx_username:
    file: /srv/growgrid/secrets/influx_username
  influx_password:
    file: /srv/growgrid/secrets/influx_password
  influx_token_telegraf:
    file: /srv/growgrid/secrets/influx_token_telegraf
  influx_token_grafana:
    file: /srv/growgrid/secrets/influx_token_grafana
  grafana_admin_user:
    file: /srv/growgrid/secrets/grafana_admin_user
  grafana_admin_password:
    file: /srv/growgrid/secrets/grafana_admin_password
