name: growgrid

x-common-security: &common-security
  read_only: true
  cap_drop: [ALL]
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

services:
  config-init:
    image: alpine:3.19
    container_name: growgrid-config-init
    volumes:
      - /srv/growgrid/config/grafana/provisioning:/src:ro
      - grafana-config:/dst
      - /srv/growgrid/secrets:/secrets:ro
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_URL: ${INFLUXDB_URL}
    command: |
      sh -c '
        export INFLUXDB_TOKEN="$(cat /secrets/influx_token_grafana)"
        mkdir -p /dst/datasources /dst/dashboards
        envsubst < /src/datasources/influxdb.yml > /dst/datasources/influxdb.yml
        envsubst < /src/dashboards/dashboards.yml > /dst/dashboards/dashboards.yml
        echo "Configuration prepared successfully"
      '
    restart: "no"

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: growgrid-mosquitto
    <<: *common-security
    read_only: false
    ports:
      - "1883:1883"
    volumes:
      - /srv/growgrid/config/mosquitto:/mosquitto/config:ro
      - /srv/growgrid/data/mosquitto:/mosquitto/data
      - /srv/growgrid/secrets:/mosquitto/secrets:ro
    tmpfs:
      - /tmp
    command: |
      sh -c '
        if [ ! -f /mosquitto/data/passwd ]; then
          mosquitto_passwd -b -c /mosquitto/data/passwd "$(cat /mosquitto/secrets/mqtt_username)" "$(cat /mosquitto/secrets/mqtt_password)"
        fi
        exec mosquitto -c /mosquitto/config/mosquitto.conf
      '

  influxdb2:
    image: influxdb:2.7-alpine
    container_name: growgrid-influxdb2
    <<: *common-security
    read_only: false
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influx_username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influx_password
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: 2160h
      INFLUXD_HTTP_BIND_ADDRESS: :8086
    env_file:
      - /srv/growgrid/.env
    secrets:
      - influx_username
      - influx_password
    volumes:
      - /srv/growgrid/data/influxdb2:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.30-alpine
    container_name: growgrid-telegraf
    <<: *common-security
    depends_on:
      - influxdb2
      - mosquitto
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_URL: ${INFLUXDB_URL}
    env_file:
      - /srv/growgrid/.env
    secrets:
      - influx_token_telegraf
      - mqtt_username
      - mqtt_password
    volumes:
      - /srv/growgrid/config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    command: |
      sh -c '
        export INFLUX_TOKEN="$(cat /run/secrets/influx_token_telegraf)"
        export MQTT_USERNAME="$(cat /run/secrets/mqtt_username)" 
        export MQTT_PASSWORD="$(cat /run/secrets/mqtt_password)"
        exec telegraf --config /etc/telegraf/telegraf.conf
      '

  grafana:
    image: grafana/grafana:10.4.5
    container_name: growgrid-grafana
    <<: *common-security
    read_only: false
    depends_on:
      config-init:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      GF_INSTALL_PLUGINS: ""
    secrets:
      - grafana_admin_user
      - grafana_admin_password
    volumes:
      - /srv/growgrid/data/grafana:/var/lib/grafana
      - grafana-config:/etc/grafana/provisioning:ro
      - /srv/growgrid/config/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  grafana-config:

secrets:
  mqtt_username:
    file: /srv/growgrid/secrets/mqtt_username
  mqtt_password:
    file: /srv/growgrid/secrets/mqtt_password
  influx_username:
    file: /srv/growgrid/secrets/influx_username
  influx_password:
    file: /srv/growgrid/secrets/influx_password
  influx_token_telegraf:
    file: /srv/growgrid/secrets/influx_token_telegraf
  influx_token_grafana:
    file: /srv/growgrid/secrets/influx_token_grafana
  grafana_admin_user:
    file: /srv/growgrid/secrets/grafana_admin_user
  grafana_admin_password:
    file: /srv/growgrid/secrets/grafana_admin_password
