{
 "title": "Growgrid",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature in [C]",
   "type": "timeseries",
   "description": "Temperature in [C]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"temperature\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Light in [Lux]",
   "type": "timeseries",
   "description": "Light in [Lux]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"light\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Soil Moisture in %",
   "type": "timeseries",
   "description": "Soil Moisture in %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"soil_moisture\")\n  |> filter(fn: (r) => r._field == \"value\")"
    }
   ]
  }
 ]
}