#pragma once

#define TASK_PRIO_MQTT_PUBLISHER 5
#define TASK_PRIO_SENSOR_SERVICE 4

#define TASK_STACK_MQTT_PUBLISHER 4096
#define TASK_STACK_SENSOR_SERVICE 2048

#define SENSOR_POLLING_INTERVAL_MS (100 * 10)
#define MQTT_PUBLISH_INTERVAL_MS (410 * 10)

#define SENSOR_QUEUE_SIZE 1
