#pragma once

#define SOIL_OUT_MAX 2200
#define SOIL_OUT_MIN 900

#define TASK_PRIO_POWER_MANGER 6
#define TASK_PRIO_SENSOR_SERVICE 4

#define TASK_STACK_POWER_PUBLISHER 4096
#define TASK_STACK_SENSOR_SERVICE 4096

#define SENSOR_READ_INTERVAL_MS (2000)

#define SENSOR_QUEUE_SIZE 10

#define EVENT_SENSOR_TEMP_BIT (1 << 0)
#define EVENT_SENSOR_LUX_BIT (1 << 1)
#define EVENT_SENSOR_SOIL_BIT (1 << 2)

#define EVENT_SENSOR_FAST_BITS (EVENT_SENSOR_TEMP_BIT | EVENT_SENSOR_LUX_BIT)
#define EVENT_SENSOR_ALL_BITS                                                  \
  (EVENT_SENSOR_TEMP_BIT | EVENT_SENSOR_LUX_BIT | EVENT_SENSOR_SOIL_BIT)
#define EVENT_SENSOR_WAIT_TIMEOUT_MS (500 * 10)

#define SHARED_DATA_SEMAPHORE_TIMEOUT_MS 2000
