#pragma once

#define SOIL_OUT_MAX 2200
#define SOIL_OUT_MIN 900

#define TASK_PRIO_MQTT_PUBLISHER 5
#define TASK_PRIO_SENSOR_SERVICE 4

#define TASK_STACK_MQTT_PUBLISHER 4096
#define TASK_STACK_SENSOR_SERVICE 2048

// #define SENSOR_POLLING_INTERVAL_MS (100 * 10)
// #define MQTT_PUBLISH_INTERVAL_MS (410 * 10)

#define SLEEP_TIME_SEC 7

#define SENSOR_QUEUE_SIZE 1

#define EVENT_SENSOR_TEMP_BIT (1 << 0)
#define EVENT_SENSOR_LUX_BIT (1 << 1)
#define EVENT_SENSOR_SOIL_BIT (1 << 2)
#define EVENT_SENSOR_ALL_BITS                                                  \
  (EVENT_SENSOR_TEMP_BIT | EVENT_SENSOR_LUX_BIT | EVENT_SENSOR_SOIL_BIT)
#define EVENT_SENSOR_WAIT_TIMEOUT_MS (5000 * 10)
