#pragma once

// Task Priorities
#define TASK_PRIO_PUMP_CONTROL 10
#define TASK_PRIO_MQTT_MANGER 6
#define TASK_PRIO_FAST_SENSOR 4
#define TASK_PRIO_SLOW_SENSOR 4

// Task Stack Sizes
#define TASK_STACK_PUMP_CONTROL 4096
#define TASK_STACK_MQTT_PUBLISHER 4096
#define TASK_STACK_FAST_SENSOR 4096
#define TASK_STACK_SLOW_SENSOR 4096

// Sensor Reading Intervals
#define FAST_SENSOR_READ_INTERVAL_MS 5000
#define SLOW_SENSOR_READ_INTERVAL_MS 5000

// Event Bus
#define EVENT_BUS_POST_TIMEOUT_MS 100
