#pragma once

// Task Priorities
#define TASK_PRIO_PUMP_CONTROL 10
#define TASK_PRIO_MQTT_MANGER 6
#define TASK_PRIO_TEMP_SENSOR 4
#define TASK_PRIO_LIGHT_SENSOR 4
#define TASK_PRIO_SOIL_SENSOR 4

// Task Stack Sizes
#define TASK_STACK_PUMP_CONTROL 4096
#define TASK_STACK_MQTT_PUBLISHER 4096
#define TASK_STACK_TEMP_SENSOR 4096
#define TASK_STACK_LIGHT_SENSOR 4096
#define TASK_STACK_SOIL_SENSOR 4096

// Sensor Reading Intervals
#define TEMP_SENSOR_READ_INTERVAL_MS 15000
#define LIGHT_SENSOR_READ_INTERVAL_MS 15000
#define SOIL_SENSOR_READ_INTERVAL_MS 15000

// Event Bus
#define EVENT_BUS_POST_TIMEOUT_MS 100
